#!/bin/bash

DEFAULT_COMMIT_MESSAGE="Aggiunto"

if [ $# -eq 0 ]; then
    COMMIT_MESSAGE="$DEFAULT_COMMIT_MESSAGE"
else
    COMMIT_MESSAGE="$1"
fi

# build the prject
# npm run build

git add .
git commit -m "$COMMIT_MESSAGE"
git push
